### ISSUE TITLE
Rename argument should not allow names with spaces

### ISSUE THREAD

**Issue by balsa-sarenac** [pharo-project/pharo#17258]
Rename argument or temporary allows renaming argument with a name that contains a space.

![Screenshot 2024-10-11 at 16 30 49](https://github.com/user-attachments/assets/bd4e3e40-6fcb-4254-9a9a-9fec83cdc6cc)

**Comment by RemiDufloer** [comment]
Hello, can you send the version of you'r image, and a description of what do you do for obtain this bug ?

**Comment by balsa-sarenac** [comment]
It should only be this issue: #17259, I'll close this one since this works as expected
